Improved test scripts, now partly OCaml Updated expected results of tests Fixed a bunch of warnings in tests for reused replication indices Improved build and distribution scripts opam package Search the default library in the directory in which cryptoverif is found out_game, out_state, and out_facts output in directory specified by -o; limit the allowed characters in filenames Avoid List.find_opt for compatibility with OCaml < 4.05

diff --git a/distrib/makedistrib b/distrib/makedistrib
--- a/distrib/makedistrib
+++ b/distrib/makedistrib
@@ -1,36 +1,56 @@
-#!/bin/sh
+#!/bin/bash
+set -e
+
+CWD=$(pwd)
+
+DIR=$(basename "$CWD")
+if [ "$DIR" != "distrib" ]
+then
+    echo "This script must be executed from within the 'distrib' directory."
+    exit 2
+fi
 
 VERSION=$1
 YEAR=`date +%Y`
 DEST=$HOME/cryptoverifreleases
-DESTD=$DEST/cryptoverif$VERSION
+DESTD="$DEST"/cryptoverif"$VERSION"
 
-echo Creating release of CryptoVerif version $VERSION
-
-if [ -d $DEST ]
+if [ -z "$1" ]
 then
-        echo
-else
-        echo Directory $DEST does not exist. Please create it.
-        exit 2
+    echo "Please indicate a version number as first argument."
+    exit 2
 fi
 
-if [ -d $DESTD ]
+
+if [ ! -d "$DEST" ]
 then
-        echo Directory $DESTD already exists. Please remove it.
-        exit 2
+    echo "Directory '$DEST' does not exist. Please create it."
+    exit 2
 fi
+
+if [ -d "$DESTD" ]
+then
+    echo "Directory '$DESTD' already exists. Please remove it."
+    exit 2
+fi
+
+echo "Creating release of CryptoVerif version '$VERSION'"
 
 cd ..
-mkdir $DESTD
+# We are now in the root directory of CryptoVerif.
 
-sed s/VERSION/$VERSION/g\;s/YEAR/$YEAR/g README > $DESTD/README
-cp CHANGES LICENSE build build.bat test $DESTD
-
-mkdir $DESTD/cryptolib $DESTD/docs $DESTD/examples $DESTD/examples/basic $DESTD/examples/obasic $DESTD/examples/kerberos $DESTD/examples/arinc823 $DESTD/examples/arinc823/sharedkey $DESTD/examples/arinc823/publickey $DESTD/examples/textsecure $DESTD/examples/tls13 $DESTD/examples/wireguard $DESTD/src $DESTD/tests $DESTD/emacs $DESTD/implementation $DESTD/implementation/nspk $DESTD/implementation/wlsk $DESTD/implementation/ssh
-
+set +e # Don't fail the script if there are no files to be removed.
 rm *~ */*~ */*/*~
+set -e
 
+# Build header file
+sed "s/YEAR/$YEAR/g" distrib/head.ml > distrib/head_year_tmp.ml
+
+# Build src/version.ml
+mv src/version.ml src/version.ml-tmp
+echo "let version = \"$VERSION\"" > src/version.ml
+
+# Build the manual
 cd docs
 pdflatex manual.tex
 bibtex manual
@@ -38,42 +58,92 @@ pdflatex manual.tex
 pdflatex manual.tex
 cd ..
 
-cp docs/manual.pdf $DESTD/docs
-cp emacs/* $DESTD/emacs
-cp implementation/nspk/README $DESTD/implementation/nspk
-cp implementation/wlsk/README $DESTD/implementation/wlsk
-cp implementation/ssh/README $DESTD/implementation/ssh
-cp implementation/nspk/build.sh $DESTD/implementation/nspk
-cp implementation/wlsk/build.sh $DESTD/implementation/wlsk
-cp implementation/ssh/build.sh $DESTD/implementation/ssh
-cp examples/arinc823/gen $DESTD/examples/arinc823
-cp examples/kerberos/*.pcv examples/kerberos/*.m4.cv $DESTD/examples/kerberos
-cp examples/textsecure/runcv $DESTD/examples/textsecure
-cp examples/tls13/runcv examples/tls13/README.md $DESTD/examples/tls13
-cp examples/wireguard/boolean_choice.cvl examples/wireguard/hashgen.ml examples/wireguard/preamble.cvl examples/wireguard/runWG.25519 examples/wireguard/separator.cvl examples/wireguard/WG.25519.dos.cv examples/wireguard/*.m4.cv $DESTD/examples/wireguard
+mkdir "$DESTD"
 
-for i in src/*.ml src/*.mli src/*.mll implementation/base.ml* implementation/crypto*.ml* implementation/nspk/A*.ml implementation/nspk/B*.ml implementation/nspk/S*.ml  implementation/nspk/test.ml implementation/nspk/nspk3tbl.ocv implementation/wlsk/init.ml implementation/wlsk/keygen.ml implementation/wlsk/resp.ml implementation/wlsk/server.ml implementation/wlsk/test_wlsk.ml implementation/wlsk/woolamskcorr_tbl.cv implementation/ssh/ssh*.ml* implementation/ssh/add_key.ml implementation/ssh/ssh*.ocv examples/basic/* examples/obasic/* examples/arinc823/arinc823prim.cvl examples/arinc823/*/*.m4.cv examples/arinc823/*/*.ocv examples/textsecure/*.m4.cv examples/tls13/*.cv* cryptolib/commonlib.cvl cryptolib/crypto.pvl cryptolib/*.ocv 
+sed "s/VERSION/$VERSION/g;s/YEAR/$YEAR/g" README > "$DESTD"/README
+
+mkdir "$DESTD"/cryptolib "$DESTD"/docs "$DESTD"/examples "$DESTD"/examples/basic "$DESTD"/examples/obasic "$DESTD"/examples/kerberos "$DESTD"/examples/arinc823 "$DESTD"/examples/arinc823/sharedkey "$DESTD"/examples/arinc823/publickey "$DESTD"/examples/textsecure "$DESTD"/examples/tls13 "$DESTD"/examples/wireguard "$DESTD"/src "$DESTD"/tests "$DESTD"/emacs "$DESTD"/implementation "$DESTD"/implementation/nspk "$DESTD"/implementation/wlsk "$DESTD"/implementation/ssh
+
+for i in CHANGES LICENSE build build.bat test docs/manual.pdf emacs/* implementation/nspk/README implementation/wlsk/README implementation/ssh/README implementation/nspk/build.sh implementation/wlsk/build.sh implementation/ssh/build.sh implementation/ssh/prepare examples/arinc823/prepare examples/kerberos/prepare examples/kerberos/*.pcv examples/kerberos/*.m4.cv examples/textsecure/prepare examples/tls13/README.md examples/wireguard/boolean_choice.cvl examples/wireguard/hashgen.ml examples/wireguard/preamble.cvl examples/wireguard/prepare examples/wireguard/separator.cvl examples/wireguard/WG.25519.dos.cv examples/wireguard/*.m4.cv src/rusage.c
 do
-        if [ -f $i ]
-        then
-                cat distrib/head.ml $i > $DESTD/$i
-        fi
-done
-for i in src/*.mly 
-do
-        if [ -f $i ]
-        then
-                (echo "%{"; cat distrib/head.ml; echo "%}"; cat $i) > $DESTD/$i
-        fi
+    cp "$i" "$DESTD/$i"
 done
 
-(cat distrib/head.ml;echo "let version = \""$VERSION\") > $DESTD/src/version.ml
+for i in src/*.ml src/*.mli src/*.mll implementation/base.ml* implementation/crypto*.ml* implementation/nspk/A*.ml implementation/nspk/B*.ml implementation/nspk/S*.ml  implementation/nspk/test.ml implementation/nspk/nspk3tbl.ocv implementation/wlsk/init.ml implementation/wlsk/keygen.ml implementation/wlsk/resp.ml implementation/wlsk/server.ml implementation/wlsk/test_wlsk.ml implementation/wlsk/woolamskcorr_tbl.cv implementation/ssh/ssh*.ml* implementation/ssh/add_key.ml implementation/ssh/ssh*.ocv examples/basic/* examples/obasic/* examples/arinc823/arinc823prim.cvl examples/arinc823/*/*.m4.cv examples/arinc823/*/*.ocv examples/textsecure/*.m4.cv examples/tls13/*.cv* cryptolib/commonlib.cvl cryptolib/crypto.pvl cryptolib/*.ocv
+do
+    if [ -f "$i" ]
+    then
+        cat distrib/head_year_tmp.ml "$i" > "$DESTD"/"$i"
+    fi
+done
 
-cp $DESTD/implementation/crypto_real.ml $DESTD/implementation/crypto.ml
+for i in src/*.mly
+do
+    if [ -f "$i" ]
+    then
+        (echo "%{"; cat distrib/head_year_tmp.ml; echo "%}"; cat "$i") > "$DESTD"/"$i"
+    fi
+done
 
-rm $DESTD/src/*lexer.ml $DESTD/src/*parser.ml $DESTD/src/*parser.mli $DESTD/src/profile.ml* 
+cp "$DESTD"/implementation/crypto_real.ml "$DESTD"/implementation/crypto.ml
 
-cd $DEST
-tar -czf $DEST/cryptoverif$VERSION.tar.gz cryptoverif$VERSION
-rm -r $DESTD
+rm "$DESTD"/src/*lexer.ml "$DESTD"/src/*parser.ml "$DESTD"/src/*parser.mli "$DESTD"/src/profile.ml*
 
+cd "$DEST"
+
+tar -czf "$DEST"/cryptoverif"$VERSION".tar.gz cryptoverif"$VERSION"
+rm -r "$DESTD"
+
+cd "$CWD"/..
+
+if uname -a | grep -E -q \(Cygwin\)\|\(MINGW\)
+then
+
+    echo "Creating binary release of CryptoVerif version '$VERSION'."
+    
+    # We are now in the root directory of CryptoVerif.
+    mkdir "$DESTD"
+    
+    # Build executables
+    ./build
+    
+    # Build wireguard.cvl
+    cd examples/wireguard
+    ./prepare
+    cd ../..
+
+    sed "s/VERSION/$VERSION/g;s/YEAR/$YEAR/g" distrib/READMEBIN > "$DESTD"/READMEBIN
+    
+    mkdir "$DESTD"/docs "$DESTD"/examples "$DESTD"/examples/basic "$DESTD"/examples/obasic "$DESTD"/examples/kerberos "$DESTD"/examples/arinc823 "$DESTD"/examples/arinc823/sharedkey "$DESTD"/examples/arinc823/publickey "$DESTD"/examples/textsecure "$DESTD"/examples/tls13 "$DESTD"/examples/wireguard "$DESTD"/tests "$DESTD"/emacs "$DESTD"/implementation "$DESTD"/implementation/nspk "$DESTD"/implementation/wlsk "$DESTD"/implementation/ssh
+    
+    for i in CHANGES LICENSE default.cvl default.ocvl cryptoverif.pvl test cryptoverif.exe cryptogen.exe analyze.exe addexpectedtags.exe docs/manual.pdf emacs/* implementation/nspk/README implementation/wlsk/README implementation/ssh/README implementation/nspk/build.sh implementation/wlsk/build.sh implementation/ssh/build.sh implementation/ssh/prepare examples/arinc823/prepare examples/kerberos/prepare examples/kerberos/*.pcv examples/kerberos/*.m4.cv examples/textsecure/prepare examples/tls13/README.md examples/wireguard/mylib.cvl examples/wireguard/prepare examples/wireguard/WG.25519.dos.cv examples/wireguard/*.m4.cv 
+    do
+	cp "$i" "$DESTD/$i"
+    done
+
+    for i in implementation/base.ml* implementation/crypto*.ml* implementation/nspk/A*.ml implementation/nspk/B*.ml implementation/nspk/S*.ml  implementation/nspk/test.ml implementation/nspk/nspk3tbl.ocv implementation/wlsk/init.ml implementation/wlsk/keygen.ml implementation/wlsk/resp.ml implementation/wlsk/server.ml implementation/wlsk/test_wlsk.ml implementation/wlsk/woolamskcorr_tbl.cv implementation/ssh/ssh*.ml* implementation/ssh/add_key.ml implementation/ssh/ssh*.ocv examples/basic/* examples/obasic/* examples/arinc823/arinc823prim.cvl examples/arinc823/*/*.m4.cv examples/arinc823/*/*.ocv examples/textsecure/*.m4.cv examples/tls13/*.cv*
+    do
+	if [ -f "$i" ]
+	then
+	    cat distrib/head_year_tmp.ml "$i" > "$DESTD"/"$i"
+	fi
+    done
+
+    cp "$DESTD"/implementation/crypto_real.ml "$DESTD"/implementation/crypto.ml
+    
+    cd "$DEST"
+    
+    zip -r "$DEST"/cryptoverifbin"$VERSION".zip cryptoverif"$VERSION"
+    rm -r "$DESTD"
+    
+else
+    echo Could not build Windows binary distribution.
+    echo You need to be under cygwin or mingw for that.
+fi
+
+# Remove temporary files
+cd "$CWD"/..
+mv src/version.ml-tmp src/version.ml
+rm distrib/head_year_tmp.ml
+
+cd "$CWD"
diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,156 +1,168 @@
 #!/bin/bash
 
-if [ -x ./xtime ]
+set -e
+cvdir=$PWD
+
+if [ ! -x ./analyze ]
 then
-    PROG=./xtime
-else
-    PROG=
+    echo ERROR analyze not found
+    exit 2
 fi
 
 if [ -d /local/bblanche/tmp ]
 then
-    TMP=/local/bblanche/tmp/tmp
+    TMPPARENT=/local/bblanche/tmp
 else
-    TMP=tmp
+    TMPPARENT=.
 fi
 
-# The arguments of analyze are
-# $1 = protocol name
-# $2 = CryptoVerif options
-# $3 = input filename (wrt the CryptoVerif directory)
-# $4 = output filename (wrt the CryptoVerif directory)
+TMPDIR="$(mktemp -d -p $TMPPARENT)"
+TMP=$TMPDIR/tmp
 
-function analyze()
+# usage message, in case of bad arguments
+
+function usage()
 {
-	echo -n PROTOCOL $1 " "
-	$PROG ./cryptoverif $2 $3 > $TMP.out 2>&1 
-	echo PROTOCOL $1 >> $4
-	cat $TMP.out >> $4
-	egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) $TMP.out > $TMP.res 
-	awk '/EXPECTED/, /END/ { print $0; }' $3 | grep -v EXPECTED | grep -v END > $TMP.expected
-	grep -v user $TMP.expected > $TMP.expectedres
-	grep -v user $TMP.res > $TMP.actualres
-	if diff -q -b $TMP.expectedres $TMP.actualres >/dev/null
-	then 
-	    echo OK
-	else
-	    echo
-	    echo RESULTS DIFFER! Expected:
-	    cat  $TMP.expectedres
-	    echo Actual:
-	    cat $TMP.actualres
-	fi
-	(echo -n "EXPECTED: "; grep user $TMP.expected ; echo -n "ACTUAL: "; grep user $TMP.res) | awk '/^EXPECTED:/ { expectedtime = substr($2, 0, length($2)-1); } /^ACTUAL:/ { actualtime = substr($2, 0, length($2)-1); } END { if (actualtime != "") { if (actualtime + 0 > expectedtime * 1.2 + 0.2) { print "Slower: old=" expectedtime " new=" actualtime}; if (actualtime + 0 < expectedtime * 0.8 - 0.2) { print "Faster: old=" expectedtime " new=" actualtime; } } }'
+    cat <<'EOF' 
+Usage: test <mode> <test_set>
+where <mode> can be:
+- test: test the mentioned scripts
+- test_add: test the mentioned scripts and add the 
+expected result in the script when it is missing
+- add: add the expected result in the script when it is missing, 
+do not test scripts that already have an expected result
+- update: test the mentioned scripts and update the expected
+result in the script
+and <test_set> can be: basic, proverif, converted, big, all, or
+dir <prefix> <list_of_directories>
+- proverif runs ProVerif on tests suitable for it
+- converted runs CryptoVerif on examples converted from CryptoVerif 1.28
+- all runs all tests included in basic, proverif, converted, and big
+- dir <prefix> <list_of_directories> analyzes the mentioned directories
+using CryptoVerif, using <prefix> as prefix for the output files.
+EOF
+    exit 2
 }
 
-function analyzepv()
+
+# analyzedirlist <prefix> <list of directories>
+# analyzes the CryptoVerif scripts in the given list of directories,
+# and outputs the results in tests/<prefix>`date`
+# with summary in tests/sum-<prefix>`date`
+# and comparison with expected results on the standard output and in tests/res-<prefix>`date`
+
+function analyzedirlist()
 {
-	echo -n PROTOCOL $1 " "
-	$PROG $HOME/proverif/proverif/proverif $2 $3 > $TMP.out 2>&1 
-	echo PROTOCOL $1 >> $4
-	cat $TMP.out >> $4
-	egrep \(PROTOCOL\|RESULT\|xtime\|Error\|user\) $TMP.out > $TMP.res 
-	awk '/EXPECTPV/, /END/ { print $0; }' $3 | grep -v EXPECTPV | grep -v END > $TMP.expected
-	grep -v user $TMP.expected > $TMP.expectedres
-	grep -v user $TMP.res > $TMP.actualres
-	if diff -q -b $TMP.expectedres $TMP.actualres >/dev/null
-	then 
-	    echo OK
-	else
-	    echo
-	    echo RESULTS DIFFER! Expected:
-	    cat  $TMP.expectedres
-	    echo Actual:
-	    cat $TMP.actualres
+    prefix=$1
+    shift
+    for dir in "$@"
+    do
+	if [ -d "$dir" ]
+	then
+	    if [ -x "$dir/prepare" ]
+	    then
+		cd "$dir"
+		./prepare
+		cd "$cvdir"
+	    fi
 	fi
-	(echo -n "EXPECTED: "; grep user $TMP.expected ; echo -n "ACTUAL: "; grep user $TMP.res) | awk '/^EXPECTED:/ { expectedtime = substr($2, 0, length($2)-1); } /^ACTUAL:/ { actualtime = substr($2, 0, length($2)-1); } END { if (actualtime != "") { if (actualtime + 0 > expectedtime * 1.2 + 0.2) { print "Slower: old=" expectedtime " new=" actualtime}; if (actualtime + 0 < expectedtime * 0.8 - 0.2) { print "Faster: old=" expectedtime " new=" actualtime; } } }'
+    done
+    ./analyze CV "$mode" "$TMPDIR" "$prefix" dirs "$@"
 }
+
+# The functions basic, proverif, converted, and big run the various
+# available tests.
+
+function basic()
+{
+    analyzedirlist test examples/basic examples/obasic examples/kerberos implementation/wlsk implementation/nspk
+
+    if [ -d examplesnd ]
+    then
+	analyzedirlist ndtest examplesnd/test examplesnd/proverif examplesnd/otest
+    fi
+}
+
+function proverif()
+{
+    echo
+    echo PROVERIF
+    echo
+    ./analyze PV "$mode" "$TMPDIR" pv dirs examples examplesnd/proverif
+}
+
+function converted()
+{
+    if [ -d examples-1.28-converted ]
+    then
+	analyzedirlist conv examples-1.28-converted
+    fi
+}
+
+function big()
+{
+    analyzedirlist textsecure examples/textsecure examplesnd/textsecure examplesnd/textsecure-keys-not-normalized examplesnd/textsecure-X448 examplesnd/textsecure-single_coord_ladder
+
+    # The TLS conference version is tested only as a converted example.
+    analyzedirlist tlsx examples/tls13
+
+    analyzedirlist arinc examples/arinc823
+    
+    if [ -d ../dev/projects/2014ANRAirbus/ICAO9880-May2017/computational ]
+    then
+	dir=../dev/projects/2014ANRAirbus/ICAO9880-May2017/computational
+    else
+	dir=$HOME/dev/projects/2014ANRAirbus/ICAO9880-May2017/computational
+    fi
+    if [ -d "$dir" ]
+    then
+	analyzedirlist icao9880-May17- "$dir"
+    fi
+
+    analyzedirlist ssh implementation/ssh
+
+    analyzedirlist WG examples/wireguard
+}
+
 
 mkdir -p tests
 
-for k in key_AK key_SK
-do
-    for loc in loc1 loc2 loc3
-    do
-	m4 -D$k -D$loc examples/kerberos/BasicKerberos_keyuse_Updated.m4.cv > examples/kerberos/BasicKerberos_keyuse.$k.$loc.cv
-	m4 -D$k -D$loc examples/kerberos/PublicKeyKerberos_keyuse_Updated.m4.cv > examples/kerberos/PublicKeyKerberos_keyuse.$k.$loc.cv
-    done
-done
+case X$1 in
+    X)  mode=test;;
+    Xtest|Xtest_add|Xadd|Xupdate)
+	mode=$1
+	shift;;
+    *)  echo "Error: unknown mode $1."
+	usage;;
+esac
 
-for key in IVCC IVSC EKCC EKSC MKCC MKSC
-do
-    m4 -DONEKEY=$key implementation/ssh/ssh-secrecy-key.m4.ocv > implementation/ssh/ssh-secrecy-key-$key.ocv
-done
-m4 implementation/ssh/ssh-secrecy-key.m4.ocv > implementation/ssh/ssh-secrecy-key.ocv
+case X$1 in
+    X|Xbasic)
+	# test
+	basic;;
+    Xproverif)
+	# test proverif
+	proverif;;
+    Xconverted)
+	# test converted
+	converted;;
+    Xbig)
+	# test big
+	big;;
+    Xall)
+	# test all  (runs all tests)
+	basic
+	proverif
+	converted
+	big;;
+    Xdir)
+	# test dir <prefix> <list of directories>
+	# analyzes the CryptoVerif scripts in the given list of directories,
+	# and outputs the results in tests/<prefix>`date`
+	shift
+	analyzedirlist "$@";;
+    *)  echo "Unknown analysis set $1"
+	usage
+esac
 
-
-echo
-echo TEST
-echo
-output=test`date '+%Y.%m.%d-%H_%M_%S'`
-(
-for i in examples/basic/*.pcv examples/basic/*.cv examples/obasic/*.ocv examples/kerberos/*.pcv examples/kerberos/*.cv
-do
-    if [ -f $i ]
-    then
-	case $i in
-	    *.m4.cv) ;;
-	    *)       analyze $i "" $i tests/$output;;
-	esac
-    fi
-done
-) | tee tests/res-$output
-egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tests/$output > tests/sum-$output
-
-
-if [ -d examplesnd ]
-then
-echo
-echo NDTEST
-echo
-output=ndtest`date '+%Y.%m.%d-%H_%M_%S'`
-rm examplesnd/*/*~ 
-(
-echo
-echo CHANNELS FRONTEND
-echo
-
-for i in examplesnd/test/* examplesnd/proverif/*.pcv implementation/wlsk/woolamskcorr_tbl.cv
-do
-    if [ -f $i ]
-    then
-	analyze $i "" $i tests/$output
-    fi
-done
-
-echo
-echo ORACLES FRONTEND
-echo
-
-for i in examplesnd/otest/* implementation/nspk/nspk3tbl.ocv implementation/ssh/ssh.ocv implementation/ssh/ssh-secrecy-key-*.ocv
-do
-    if [ -f $i ]
-    then
-	analyze $i "-in oracles" $i tests/$output
-    fi
-done
-) | tee tests/res-$output
-egrep \(PROTOCOL\|'RESULT Could not prove'\|'All queries proved'\|xtime\|Error\|user\) tests/$output > tests/sum-$output
-fi
-
-echo
-echo PROVERIF
-echo
-output=pv`date '+%Y.%m.%d-%H_%M_%S'`
-(
-for i in examples/*/*.pcv examplesnd/proverif/*.pv examplesnd/proverif/*.pcv
-do
-    if [ -f $i ]
-    then
-	    analyzepv $i "-lib cryptoverif.pvl" $i tests/$output
-    fi
-done
-) | tee tests/res-$output
-egrep \(PROTOCOL\|RESULT\|xtime\|Error\|user\) tests/$output > tests/sum-$output
-
-rm $TMP.*
+rm -r "$TMPDIR"
